name: lunabase CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  win_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fftw
      run: |
        echo "PWD is "
        pwd
        echo "Home is " ${HOME} 
        cd ${HOME}
        echo "Now PWD is"
        pwd
        choco install wget
        wget http://www.fftw.org/fftw-3.3.8.tar.gz
        tar -xzvf fftw-3.3.8.tar.gz
        cd fftw-3.3.8
        ./configure --enable-shared --prefix=${HOME}/fftw-3.3.8/
        make
        make install
        echo "GITHUB workspace is" ${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
    - name: Make
      run: |
        make ARCH=WINDOWS FFTW=${HOME}/fftw-3.3.8
        ./luna

