name: lunabase CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fftw
        run: |
          cd ${HOME}
          wget http://www.fftw.org/fftw-3.3.8.tar.gz
          tar -xzvf fftw-3.3.8.tar.gz
          cd fftw-3.3.8
          ./configure --enable-shared --prefix=${HOME}/fftw-3.3.8/
          make
          make install
          cd ${GITHUB_WORKSPACE}
      - name: make
        run: |
          make FFTW=${HOME}/fftw-3.3.8
          tar cvzf ubuntu-luna.tar.gz luna behead destrat
          ls -lrt
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-luna.tar.gz
          path: ubuntu-luna.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          path: /home/runner/work/luna-base/luna-base/download_artifacts/
          
      - run: |
          echo ${{steps.download.outputs.download-path}}
          cd ${{steps.download.outputs.download-path}}
          ls -lrt
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Win_Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset Win
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: win-luna.zip
          asset_name: win-luna.zip
          asset_content_type: application/zip
      - name: Upload Release Asset Mac
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mac-luna.tar.gz
          asset_name: win-luna.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset Ubuntu
        id: upload-release-asset-ubuntu 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ubuntu-luna.tar.gz
          asset_name: ubuntu-luna.tar.gz
          asset_content_type: application/gzip
