name: lunabase CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  windows-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-fftw
      - uses: msys2/setup-msys2@v2
      - name: Make
        run: |
          ls /mingw64/bin
          mingw32-make.exe ARCH=WINDOWS
          ls *.exe
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fftw
        run: |
          cd $HOME
          wget http://www.fftw.org/fftw-3.3.8.tar.gz
          tar -xzvf fftw-3.3.8.tar.gz
          cd fftw-3.3.8
          ./configure --enable-shared --prefix=${HOME}/fftw-3.3.8/
          make
          make install
          cd ${GITHUB_WORKSPACE}
      - name: Make
        run: make arch=MAC FFTW=${HOME}/fftw-3.3.8
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fftw
      run: |
        cd ${HOME}
        wget http://www.fftw.org/fftw-3.3.8.tar.gz
        tar -xzvf fftw-3.3.8.tar.gz
        cd fftw-3.3.8
        ./configure --enable-shared --prefix=${HOME}/fftw-3.3.8/
        make
        make install
        cd ${GITHUB_WORKSPACE}
    - name: make
      run: make FFTW=${HOME}/fftw-3.3.8
