name: lunabase CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  win_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install fftw
      run: |
        echo ::add-path::C:\msys64\usr\bin\
        pacman -S mingw-w64-x86_64-fftw
      shell: pwsh
    - name: Make
      run: |
        make ARCH=WINDOWS

